# Generated by Django 5.0.1 on 2024-02-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateField(verbose_name='Review Date')),
                ('rating', models.CharField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default='*****', max_length=1)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
