# Generated by Django 5.0.1 on 2024-02-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='yelp_api_id',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
